spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.137.128:3306/sweetmall_sms?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        server-addr: 192.168.0.110:8848
  application:
    name: sweetmall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000

